# -*- coding: utf-8 -*-
"""
/***************************************************************************
 flightPathAnalysis
                                 A QGIS plugin
 Analysis the flight path impact on UWR
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-28
        copyright            : (C) 2023 by Erica Liu
        email                : halamay1029@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Erica Liu'
__date__ = '2023-02-28'
__copyright__ = '(C) 2023 by Erica Liu'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load flightPathAnalysis class from file flightPathAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flightPathAnalysis import flightPathAnalysisPlugin
    return flightPathAnalysisPlugin()
