# -*- coding: utf-8 -*-

"""
/***************************************************************************
 flightPathAnalysis
                                 A QGIS plugin
 Analysis the flight path impact on UWR
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-02-28
        copyright            : (C) 2023 by Erica Liu
        email                : halamay1029@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Erica Liu'
__date__ = '2023-02-28'
__copyright__ = '(C) 2023 by Erica Liu'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterString,
                       QgsProcessingParameterField,
                       QgsProcessingParameterDistance,
                       QgsProcessingFeedback,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterMultipleLayers)
import glob
import os
import processing


class flightPathAnalysisAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    origUWR = 'origUWR'
    DEM = 'DEM'
    gpxFolder = 'gpxFolder'
    uwrBuffered = 'uwrBuffered'
    unit_id = 'unit_id'
    unit_id_no = 'unit_id_no'
    buffDistIS_high = 'buffDistIS_high'
    buffDistIS_moderate = 'buffDistIS_moderate'
    buffDistIS_low = 'buffDistIS_low'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
        # ===========================================================================
        # OrigUWR - Input vector polygon
        # ===========================================================================
        self.addParameter(QgsProcessingParameterFeatureSource(
            self.origUWR, self.tr('Input original UWR'), [QgsProcessing.TypeVectorPolygon]))
        # ===========================================================================
        # DEM - Input Raster
        # ===========================================================================
        self.addParameter(QgsProcessingParameterRasterLayer(
            self.DEM, self.tr('Input project DEM')))
        # ===========================================================================
        # gpx - Input Folder
        # will loop through all the gpx files under the folder
        # ===========================================================================
        self.addParameter(QgsProcessingParameterFile(
            self.gpxFolder, self.tr('Input gpx folder'), QgsProcessingParameterFile.Folder,
        ))
        # ===========================================================================
        # unit_id / unit_id_no - Input string
        # User selects from the field list derived from OrigUWR
        # ===========================================================================
        self.addParameter(QgsProcessingParameterField(
            self.unit_id, self.tr('Input unit id field, column has text like u-2-002'), 'unit_id', self.origUWR))

        self.addParameter(QgsProcessingParameterField(
            self.unit_id_no, self.tr('Input unit id field, column has text like Mg-059'), 'unit_id', self.origUWR))
        # ===========================================================================
        # bufferDistIS_high/moderate/low - Input string, with default value 500/1000/1500
        # three buffer range represents different incursion severity range
        # ===========================================================================
        self.addParameter(QgsProcessingParameterString(
            self.buffDistIS_high, self.tr('Buffer distance - High Incursion Severity'), 500))

        self.addParameter(QgsProcessingParameterString(
            self.buffDistIS_moderate, self.tr('Buffer distance - Moderate Incursion Severity'), 1000))

        self.addParameter(QgsProcessingParameterString(
            self.buffDistIS_low, self.tr('Buffer distance - Low Incursion Severity'), 1500))
        # ===========================================================================
        # uwrBuffered - output buffered layer
        # ===========================================================================
        self.addParameter(QgsProcessingParameterFeatureSink(
            self.uwrBuffered, self.tr('Output buffered layer')))

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.origUWR, context)
        origUWR = parameters['origUWR']
        gpxFolder = parameters['gpxFolder']
        feedback.setProgressText(str(origUWR))
        uwrBuffered = parameters['uwrBuffered']

        # ===========================================================================
        # Check if the input vector includes invalid geometry
        # ===========================================================================
        result = processing.run("qgis:checkvalidity", {
            'INPUT_LAYER': parameters['origUWR']})
        errorCount = result['ERROR_COUNT']
        feedback.setProgressText(str(errorCount))

        # ===========================================================================
        # Fix the input geometry if invalid found, and replace the input for further process
        # ===========================================================================
        if errorCount > 0:
            fixGeom = processing.run("native:fixgeometries", {
                'INPUT': parameters['origUWR'],
                'OUTPUT': 'TEMPORARY_OUTPUT'})
            feedback.setProgressText('Geometry fixed')
            origUWR = fixGeom['OUTPUT']

        # ===========================================================================
        # Loop through the input GPX folder and get all the gpx files
        # ===========================================================================
        gpxFiles = glob.glob(os.path.join(gpxFolder, "*.gpx"))
        count = 0
        for gpxFile in gpxFiles:
            count += 1
            feedback.setProgressText(str(count))
            feedback.setProgressText(str(gpxFile))

        (sink, dest_id) = self.parameterAsSink(parameters, self.uwrBuffered,
                                               context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.

        return {self.uwrBuffered: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Create UWR buffer'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return '2023_Project'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return flightPathAnalysisAlgorithm()
